In [0]:
import numpy as np

In [0]:
# Setup for questions 1 and 2
arr1=np.arange(40).reshape(8,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [0]:
# Q1. From arr1 you have to fetch out every alternate column starting from col1
import numpy as np
arr1=np.arange(40).reshape(8,5)
arr1[:,np.arange(0,6,2)]



array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24],
       [25, 27, 29],
       [30, 32, 34],
       [35, 37, 39]])

In [0]:
# Q2. From arr1 fetch an array which would contain {0,2,4} {15,17,19} and {30,32,34} 
import numpy as np
arr1=np.arange(40).reshape(8,5)
a=arr1[:,np.arange(0,5,2)]
a[np.arange(0,8,3),:]

array([[ 0,  2,  4],
       [15, 17, 19],
       [30, 32, 34]])

In [0]:
# Setup for question

# Generating a random numpy array of intergers ranging between 1 and 100

arr2=np.random.randint(low=1, high=100, size=10).reshape(2,5)
arr2

array([[71, 93, 89, 28, 63],
       [40, 97, 77, 19, 13]])

 **Normalization** rescales the values into a range of [0,1]. This might be useful in some cases where all parameters need to have the same positive scale. You have to do this a lot in machine learning for eg you are working with 2 cols, one is total runs scored by a batsman(in the scale of 1000s), and the second is number of matches played by him(in the scale of 10s). The formula for normalization is given below

 Xchanged=(X−Xmin)/(Xmax−Xmin)

In [0]:
# Q3. Write a code to normalize arr2.
import numpy as np
arr2=np.random.randint(low=1, high=10000, size=10).reshape(2,5)
print(arr2)
Xmax=arr2.max()
Xmin=arr2.min()
d=Xmax-Xmin
arr2=(arr2-Xmin)/d
print(arr2)
  

[[1661 6076 9692 7373 2128]
 [2482 7372 6382 3195 9344]]
[[0.         0.54974474 1.         0.71124393 0.05814967]
 [0.10222886 0.71111941 0.58784709 0.19100984 0.95666791]]


In [0]:
np.percentile(arr1,25)

9.75

Missing values are a pain in the a**(sorry for language). But yes trust me.

In [0]:
# Q4. How would you check if your numpy array has some missing values?

import numpy as np
arr=np.array([1,2,np.nan,3,4,5])
np.isnan(arr)

# Hint: Thoda research karo numpy me existing functions hai

array([False, False,  True, False, False, False])

In [0]:
# Q5. Write a function which will accept 2 arguments.
# First: A 1D numpy array arr
# Second: An integer n {Please make sure n<=len(arr)}

# Output: The output should be the nth largest item out of the array

# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40



In [0]:
def ans(arr,n):
  arr.sort()
  b=arr[::-1]
  l=arr.size
  for i in range(0,l+1):
    if(i==n-1):
      print(b[n-1])

In [0]:
a=np.array([11,56,8,9,67,90,1])
ans(a,3)

56


In [0]:
ans(a,1)

90
